language: node_js
node_js:
  - stable
  - lts/*

install:
  - npm ci

git:
  depth: 1

script:
  - npm run test

after_script:
  - npm run ci-cover

before_deploy:
  - npm run build

deploy:
  provider: npm
  email: $NPM_PUBLIC_EMAIL
  api_key: $NPM_API_KEY
  skip_cleanup: true
  on:
    tags: true